name: Javascript

on: [pull_request, push]

jobs:
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Format
        run: npx prettier --check web

      - name: Lint
        run: npx oxlint -c oxlintrc.json web
